### ISSUE TITLE
Allow to copy/paste snapshots of isotherms

### ISSUE THREAD

**Issue by danieleongari** [NIST-ISODB/isotherm-digitizer-panel#65] opened 2020-11-03 21:11 UTC
The Web Plot Digitizer (https://apps.automeris.io/wpd/) allow to make a snapshot of your screen and paste directly it in the app with CTRL-V.
This is very convenient because you don't have to save, look for the file, and upload it: you just make a snapshot of the figure you want to digitize and you paste it. This works well for Ubuntu and MacOs.

Currently, saving/uploading is still necessary for the isother-digitizer-panel, also making the risk of swapping files.
It would be very nice to have the possibility to do the same, 
and even nicer to display the figure in both the filling and plot tabs, to help the user to avoid confusion between isotherms.

**Comment by ltalirz** [comment] 2020-11-05 21:55
Closing as a duplicate of #42

**Closed as completed by ltalirz** 2020-11-05 21:55 UTC
